name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger workflow khi có thay đổi trên nhánh main(check ok)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Sử dụng runner Ubuntu từ GitHub

    steps:
    # Bước 1: Lấy mã nguồn từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Thiết lập SSH key để kết nối tới EC2
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # Bước 3: Thêm địa chỉ EC2 vào known_hosts
    - name: Add EC2 host to known hosts
      run: |
        ssh-keyscan -H 3.1.81.58 >> ~/.ssh/known_hosts

    # Bước 4: Sao chép file index.html lên EC2
    - name: Deploy index.html to EC2
      run: |
        scp -i ~/.ssh/id_rsa index.html ubuntu@3.1.81.58:/var/www/html/

    # Bước 5: Khởi động lại Nginx trên EC2
    - name: Restart web server (Nginx)
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.1.81.58 "sudo systemctl restart nginx"
